"""init

Revision ID: 7f0fb9a303df
Revises: 
Create Date: 2025-05-04 19:47:12.231854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0fb9a303df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('AVATAR_NO', sa.Integer(), nullable=False),
    sa.Column('AVATAR_NM', sa.String(), nullable=False),
    sa.Column('AVATAR_TYPE', sa.Enum('CHARACTER', 'PET', name='AvatarType'), nullable=True),
    sa.PrimaryKeyConstraint('AVATAR_NO')
    )
    op.create_table('challenge_master',
    sa.Column('CHALLENGE_MST_NO', sa.Integer(), nullable=False),
    sa.Column('CHALLENGE_MST_NM', sa.String(), nullable=True),
    sa.Column('START_DT', sa.DateTime(), nullable=True),
    sa.Column('END_DT', sa.DateTime(), nullable=True),
    sa.Column('HEADER_EMOJI', sa.String(), nullable=True),
    sa.Column('CHALLENGE_STATUS', sa.Enum('PENDING', 'PROGRESS', 'COMPLETE', 'FAILED', name='ChallengeStatusType'), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('MODIFY_DT', sa.DateTime(), nullable=True),
    sa.Column('DELETE_DT', sa.DateTime(), nullable=True),
    sa.Column('DELETE_YN', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('CHALLENGE_MST_NO')
    )
    op.create_table('item',
    sa.Column('ITEM_NO', sa.Integer(), nullable=False),
    sa.Column('ITEM_NM', sa.Enum('BOOM', 'HAMMER', name='ItemType'), nullable=False),
    sa.PrimaryKeyConstraint('ITEM_NO')
    )
    op.create_table('user',
    sa.Column('USER_NO', sa.Integer(), nullable=False),
    sa.Column('SIGN_TYPE', sa.Enum('KAKAO', 'APPLE', 'GUEST', name='SignType'), nullable=True),
    sa.Column('USER_NM', sa.String(), nullable=True),
    sa.Column('UID', sa.Integer(), nullable=True),
    sa.Column('USER_EMAIL', sa.String(), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('MODIFY_DT', sa.DateTime(), nullable=True),
    sa.Column('RECENT_LOGIN_DT', sa.DateTime(), nullable=True),
    sa.Column('DISABLE_YN', sa.Boolean(), nullable=True),
    sa.Column('DISABLE_DT', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('USER_NO')
    )
    op.create_index(op.f('ix_user_UID'), 'user', ['UID'], unique=True)
    op.create_table('avatar_user',
    sa.Column('AVATAR_USER_NO', sa.Integer(), nullable=False),
    sa.Column('IS_EQUIP', sa.Boolean(), nullable=True),
    sa.Column('AVATAR_NO', sa.Integer(), nullable=True),
    sa.Column('USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AVATAR_NO'], ['avatar.AVATAR_NO'], ),
    sa.ForeignKeyConstraint(['USER_NO'], ['user.USER_NO'], ),
    sa.PrimaryKeyConstraint('AVATAR_USER_NO')
    )
    op.create_table('challenge_users',
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=False),
    sa.Column('ACCEPT_STATUS', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'DELETED', name='InviteAcceptType'), nullable=True),
    sa.Column('COMMENT', sa.String(), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('MODIFY_DT', sa.DateTime(), nullable=True),
    sa.Column('IS_OWNER', sa.Boolean(), nullable=True),
    sa.Column('IS_VIEW', sa.Boolean(), nullable=True),
    sa.Column('USER_NO', sa.Integer(), nullable=True),
    sa.Column('CHALLENGE_MST_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_MST_NO'], ['challenge_master.CHALLENGE_MST_NO'], ),
    sa.ForeignKeyConstraint(['USER_NO'], ['user.USER_NO'], ),
    sa.PrimaryKeyConstraint('CHALLENGE_USER_NO')
    )
    op.create_table('friend',
    sa.Column('FRIEND_NO', sa.Integer(), nullable=False),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('ACCEPT_DT', sa.DateTime(), nullable=True),
    sa.Column('InviteAcceptType', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'DELETED', name='inviteaccepttype'), nullable=True),
    sa.Column('SENDER_NO', sa.Integer(), nullable=True),
    sa.Column('RECIPIENT_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RECIPIENT_NO'], ['user.USER_NO'], ),
    sa.ForeignKeyConstraint(['SENDER_NO'], ['user.USER_NO'], ),
    sa.PrimaryKeyConstraint('FRIEND_NO')
    )
    op.create_table('user_setting',
    sa.Column('USER_SETTING_NO', sa.Integer(), nullable=False),
    sa.Column('AGREE_POLICY_YN', sa.Boolean(), nullable=True),
    sa.Column('AGREE_POLICY_DT', sa.DateTime(), nullable=True),
    sa.Column('NOTICE_PUSH_YN', sa.Boolean(), nullable=True),
    sa.Column('NOTICE_PUSH_DT', sa.DateTime(), nullable=True),
    sa.Column('NOTICE_PUSH_AD_YN', sa.Boolean(), nullable=True),
    sa.Column('NOTICE_PUSH_AD_DT', sa.DateTime(), nullable=True),
    sa.Column('NOTICE_PUSH_NIGHT_YN', sa.Boolean(), nullable=True),
    sa.Column('NOTICE_PUSH_NIGHT_DT', sa.DateTime(), nullable=True),
    sa.Column('USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['USER_NO'], ['user.USER_NO'], ),
    sa.PrimaryKeyConstraint('USER_SETTING_NO')
    )
    op.create_table('additional_goal',
    sa.Column('ADDITIONAL_NO', sa.Integer(), nullable=False),
    sa.Column('ADDITIONAL_NM', sa.String(), nullable=True),
    sa.Column('IS_DONE', sa.Boolean(), nullable=True),
    sa.Column('START_DT', sa.DateTime(), nullable=True),
    sa.Column('END_DT', sa.DateTime(), nullable=True),
    sa.Column('IMAGE_FILE_NM', sa.String(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.PrimaryKeyConstraint('ADDITIONAL_NO')
    )
    op.create_table('item_log',
    sa.Column('ITEM_LOG_NO', sa.Integer(), nullable=False),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('IS_VIEW', sa.Boolean(), nullable=True),
    sa.Column('SENDER_NO', sa.Integer(), nullable=True),
    sa.Column('RECIPIENT_NO', sa.Integer(), nullable=True),
    sa.Column('ITEM_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ITEM_NO'], ['item.ITEM_NO'], ),
    sa.ForeignKeyConstraint(['RECIPIENT_NO'], ['challenge_users.CHALLENGE_USER_NO'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SENDER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ITEM_LOG_NO')
    )
    op.create_table('item_user',
    sa.Column('ITEM_USER_NO', sa.Integer(), nullable=False),
    sa.Column('COUNT', sa.Integer(), nullable=True),
    sa.Column('ITEM_NO', sa.Integer(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.ForeignKeyConstraint(['ITEM_NO'], ['item.ITEM_NO'], ),
    sa.PrimaryKeyConstraint('ITEM_USER_NO')
    )
    op.create_table('person_daily_goal_complete',
    sa.Column('DAILY_COMPLETE_NO', sa.Integer(), nullable=False),
    sa.Column('IMAGE_FILE_NM', sa.String(), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('COMMENT', sa.String(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.PrimaryKeyConstraint('DAILY_COMPLETE_NO')
    )
    op.create_table('daily_complete_user',
    sa.Column('DAILY_COMPLETE_USER_NO', sa.Integer(), nullable=False),
    sa.Column('EMOJI', sa.String(), nullable=True),
    sa.Column('DAILY_COMPLETE_NO', sa.Integer(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.ForeignKeyConstraint(['DAILY_COMPLETE_NO'], ['person_daily_goal_complete.DAILY_COMPLETE_NO'], ),
    sa.PrimaryKeyConstraint('DAILY_COMPLETE_USER_NO')
    )
    op.create_table('person_daily_goal',
    sa.Column('PERSON_NO', sa.Integer(), nullable=False),
    sa.Column('PERSON_NM', sa.String(), nullable=True),
    sa.Column('IS_DONE', sa.Boolean(), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('UPDATE_DT', sa.DateTime(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.Column('DAILY_COMPLETE_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.ForeignKeyConstraint(['DAILY_COMPLETE_NO'], ['person_daily_goal_complete.DAILY_COMPLETE_NO'], ),
    sa.PrimaryKeyConstraint('PERSON_NO')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_daily_goal')
    op.drop_table('daily_complete_user')
    op.drop_table('person_daily_goal_complete')
    op.drop_table('item_user')
    op.drop_table('item_log')
    op.drop_table('additional_goal')
    op.drop_table('user_setting')
    op.drop_table('friend')
    op.drop_table('challenge_users')
    op.drop_table('avatar_user')
    op.drop_index(op.f('ix_user_UID'), table_name='user')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('challenge_master')
    op.drop_table('avatar')
    # ### end Alembic commands ###
