"""fix error 2

Revision ID: d8db17fa6ebc
Revises: ddea7b1dcef0
Create Date: 2025-05-04 19:57:42.729249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8db17fa6ebc'
down_revision: Union[str, None] = 'ddea7b1dcef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # 0) 이미 자동 생성된 ALTER … SET START WITH … 문은 지워 버리세요.
    #
    # 1) UID 컬럼에 남아 있을 기존 DEFAULT 제거
    op.execute("""
        ALTER TABLE "user"
        ALTER COLUMN "UID" DROP DEFAULT
    """)

    # 2) 예전 시퀀스가 있으면 삭제(선택)
    op.execute("""
        DROP SEQUENCE IF EXISTS user_uid_seq
    """)

    # 3) IDENTITY 속성 부여 + 시작값 1,000,000
    op.execute("""
        ALTER TABLE "user"
        ALTER COLUMN "UID"
        ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000)
    """)

def downgrade():
    # 필요하면 되돌리는 로직을 작성
    op.execute("""
        ALTER TABLE "user"
        ALTER COLUMN "UID" DROP IDENTITY IF EXISTS
    """)
    op.execute("""
        CREATE SEQUENCE user_uid_seq START 1000000;
        ALTER TABLE "user"
        ALTER COLUMN "UID" SET DEFAULT nextval('user_uid_seq')
    """)
