"""fix error

Revision ID: ddea7b1dcef0
Revises: 7f0fb9a303df
Create Date: 2025-05-04 19:52:36.027346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddea7b1dcef0'
down_revision: Union[str, None] = '7f0fb9a303df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_users', 'ACCEPT_STATUS',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'DELETED', name='InviteAcceptType'),
               nullable=False)
    op.add_column('friend', sa.Column('ACCEPT_STATUS', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'DELETED', name='InviteAcceptType'), nullable=False))
    op.drop_column('friend', 'InviteAcceptType')
    op.alter_column('user', 'UID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'UID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('friend', sa.Column('InviteAcceptType', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'DELETED', name='inviteaccepttype'), autoincrement=False, nullable=True))
    op.drop_column('friend', 'ACCEPT_STATUS')
    op.alter_column('challenge_users', 'ACCEPT_STATUS',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'DELETED', name='InviteAcceptType'),
               nullable=True)
    # ### end Alembic commands ###
